version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www
